--
-- FECHA CREACIÓN		    : 01-02-2026
-- FECHA DE MODIFICACIÓN: 19-03-2026
--

-- 1. Crear usuario
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_roles WHERE rolname = 'allpa'
    ) THEN
        CREATE USER allpa WITH PASSWORD '123';
    END IF;
END
$$;

-- 2. Permitir conexión a la base de datos
GRANT CONNECT ON DATABASE allpa TO allpa;

-- 3. Permitir acceso a los esquemas
GRANT USAGE ON SCHEMA catastro TO allpa;
GRANT USAGE ON SCHEMA cofopri TO allpa;
GRANT USAGE ON SCHEMA geo TO allpa;
GRANT USAGE ON SCHEMA ign TO allpa;
GRANT USAGE ON SCHEMA ingemmet TO allpa;
GRANT USAGE ON SCHEMA midagri TO allpa;
GRANT USAGE ON SCHEMA sbn TO allpa;

-- 4. Permisos de lectura sobre todas las tablas existentes
GRANT SELECT ON ALL TABLES IN SCHEMA catastro TO allpa;
GRANT SELECT ON ALL TABLES IN SCHEMA cofopri TO allpa;
GRANT SELECT ON ALL TABLES IN SCHEMA geo TO allpa;
GRANT SELECT ON ALL TABLES IN SCHEMA ign TO allpa;
GRANT SELECT ON ALL TABLES IN SCHEMA ingemmet TO allpa;
GRANT SELECT ON ALL TABLES IN SCHEMA midagri TO allpa;
GRANT SELECT ON ALL TABLES IN SCHEMA sbn TO allpa;

-- 5. Permisos sobre secuencias
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA catastro TO allpa;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA cofopri TO allpa;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA geo TO allpa;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ign TO allpa;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ingemmet TO allpa;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA midagri TO allpa;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA sbn TO allpa;

-- 6. Permisos por defecto para tablas futuras
ALTER DEFAULT PRIVILEGES IN SCHEMA catastro
GRANT SELECT ON TABLES TO allpa;

ALTER DEFAULT PRIVILEGES IN SCHEMA cofopri
GRANT SELECT ON TABLES TO allpa;

ALTER DEFAULT PRIVILEGES IN SCHEMA geo
GRANT SELECT ON TABLES TO allpa;

ALTER DEFAULT PRIVILEGES IN SCHEMA ign
GRANT SELECT ON TABLES TO allpa;

ALTER DEFAULT PRIVILEGES IN SCHEMA ingemmet
GRANT SELECT ON TABLES TO allpa;

ALTER DEFAULT PRIVILEGES IN SCHEMA midagri
GRANT SELECT ON TABLES TO allpa;

ALTER DEFAULT PRIVILEGES IN SCHEMA sbn
GRANT SELECT ON TABLES TO allpa;

-- 7. Permisos por defecto para secuencias futuras
ALTER DEFAULT PRIVILEGES IN SCHEMA catastro
GRANT USAGE, SELECT ON SEQUENCES TO allpa;

ALTER DEFAULT PRIVILEGES IN SCHEMA cofopri
GRANT USAGE, SELECT ON SEQUENCES TO allpa;

ALTER DEFAULT PRIVILEGES IN SCHEMA geo
GRANT USAGE, SELECT ON SEQUENCES TO allpa;

ALTER DEFAULT PRIVILEGES IN SCHEMA ign
GRANT USAGE, SELECT ON SEQUENCES TO allpa;

ALTER DEFAULT PRIVILEGES IN SCHEMA ingemmet
GRANT USAGE, SELECT ON SEQUENCES TO allpa;

ALTER DEFAULT PRIVILEGES IN SCHEMA midagri
GRANT USAGE, SELECT ON SEQUENCES TO allpa;

ALTER DEFAULT PRIVILEGES IN SCHEMA sbn
GRANT USAGE, SELECT ON SEQUENCES TO allpa;

GRANT SELECT ON ALL TABLES IN SCHEMA catastro TO allpa;
GRANT SELECT ON TABLE catastro.tf_fichas TO allpa;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA catastro
GRANT SELECT ON TABLES TO allpa;

-- 8. Definir search_path
ALTER ROLE allpa SET search_path TO catastro, cofopri, geo, ign, ingemmet, midagri, public, sbn;